// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pkg/smgrpc/smgrpc.proto

package smgrpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sent bool `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

type NetProtoTalker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proto string `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Bytes uint32 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Rate  uint32 `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *NetProtoTalker) Reset() {
	*x = NetProtoTalker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetProtoTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetProtoTalker) ProtoMessage() {}

func (x *NetProtoTalker) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetProtoTalker.ProtoReflect.Descriptor instead.
func (*NetProtoTalker) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{1}
}

func (x *NetProtoTalker) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *NetProtoTalker) GetBytes() uint32 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *NetProtoTalker) GetRate() uint32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type NetRateTalker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proto string `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Sport uint32 `protobuf:"varint,2,opt,name=sport,proto3" json:"sport,omitempty"`
	Dport uint32 `protobuf:"varint,3,opt,name=dport,proto3" json:"dport,omitempty"`
	Bps   uint32 `protobuf:"varint,4,opt,name=bps,proto3" json:"bps,omitempty"`
}

func (x *NetRateTalker) Reset() {
	*x = NetRateTalker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetRateTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetRateTalker) ProtoMessage() {}

func (x *NetRateTalker) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetRateTalker.ProtoReflect.Descriptor instead.
func (*NetRateTalker) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{2}
}

func (x *NetRateTalker) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *NetRateTalker) GetSport() uint32 {
	if x != nil {
		return x.Sport
	}
	return 0
}

func (x *NetRateTalker) GetDport() uint32 {
	if x != nil {
		return x.Dport
	}
	return 0
}

func (x *NetRateTalker) GetBps() uint32 {
	if x != nil {
		return x.Bps
	}
	return 0
}

type Fs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Used  uint32 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Iused uint32 `protobuf:"varint,3,opt,name=iused,proto3" json:"iused,omitempty"`
}

func (x *Fs) Reset() {
	*x = Fs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fs) ProtoMessage() {}

func (x *Fs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fs.ProtoReflect.Descriptor instead.
func (*Fs) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{3}
}

func (x *Fs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fs) GetUsed() uint32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *Fs) GetIused() uint32 {
	if x != nil {
		return x.Iused
	}
	return 0
}

type Listen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   string `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	User  string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Pid   uint32 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Proto string `protobuf:"bytes,4,opt,name=proto,proto3" json:"proto,omitempty"`
	Port  uint32 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Listen) Reset() {
	*x = Listen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listen) ProtoMessage() {}

func (x *Listen) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listen.ProtoReflect.Descriptor instead.
func (*Listen) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{4}
}

func (x *Listen) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Listen) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Listen) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Listen) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *Listen) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type LoadAverage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Load uint32 `protobuf:"varint,1,opt,name=load,proto3" json:"load,omitempty"`
}

func (x *LoadAverage) Reset() {
	*x = LoadAverage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAverage) ProtoMessage() {}

func (x *LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAverage.ProtoReflect.Descriptor instead.
func (*LoadAverage) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{5}
}

func (x *LoadAverage) GetLoad() uint32 {
	if x != nil {
		return x.Load
	}
	return 0
}

type Cpu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sys  uint32 `protobuf:"varint,1,opt,name=sys,proto3" json:"sys,omitempty"`
	User uint32 `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Idle uint32 `protobuf:"varint,3,opt,name=idle,proto3" json:"idle,omitempty"`
}

func (x *Cpu) Reset() {
	*x = Cpu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cpu) ProtoMessage() {}

func (x *Cpu) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cpu.ProtoReflect.Descriptor instead.
func (*Cpu) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{6}
}

func (x *Cpu) GetSys() uint32 {
	if x != nil {
		return x.Sys
	}
	return 0
}

func (x *Cpu) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *Cpu) GetIdle() uint32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type Disk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tps  uint32 `protobuf:"varint,1,opt,name=tps,proto3" json:"tps,omitempty"`
	Kbps uint32 `protobuf:"varint,2,opt,name=kbps,proto3" json:"kbps,omitempty"`
}

func (x *Disk) Reset() {
	*x = Disk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{7}
}

func (x *Disk) GetTps() uint32 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *Disk) GetKbps() uint32 {
	if x != nil {
		return x.Kbps
	}
	return 0
}

type TcpConnections struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TcpConnections) Reset() {
	*x = TcpConnections{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcpConnections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpConnections) ProtoMessage() {}

func (x *TcpConnections) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpConnections.ProtoReflect.Descriptor instead.
func (*TcpConnections) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{8}
}

func (x *TcpConnections) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type All struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadAverage  *LoadAverage      `protobuf:"bytes,1,opt,name=loadAverage,proto3" json:"loadAverage,omitempty"`
	Cpu          *Cpu              `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Disk         *Disk             `protobuf:"bytes,3,opt,name=disk,proto3" json:"disk,omitempty"`
	Partitions   []*Fs             `protobuf:"bytes,4,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Connections  *TcpConnections   `protobuf:"bytes,5,opt,name=connections,proto3" json:"connections,omitempty"`
	Listners     []*Listen         `protobuf:"bytes,6,rep,name=listners,proto3" json:"listners,omitempty"`
	ProtoTalkers []*NetProtoTalker `protobuf:"bytes,7,rep,name=protoTalkers,proto3" json:"protoTalkers,omitempty"`
	RateTalker   []*NetRateTalker  `protobuf:"bytes,8,rep,name=rateTalker,proto3" json:"rateTalker,omitempty"`
}

func (x *All) Reset() {
	*x = All{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *All) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*All) ProtoMessage() {}

func (x *All) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_smgrpc_smgrpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use All.ProtoReflect.Descriptor instead.
func (*All) Descriptor() ([]byte, []int) {
	return file_pkg_smgrpc_smgrpc_proto_rawDescGZIP(), []int{9}
}

func (x *All) GetLoadAverage() *LoadAverage {
	if x != nil {
		return x.LoadAverage
	}
	return nil
}

func (x *All) GetCpu() *Cpu {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *All) GetDisk() *Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *All) GetPartitions() []*Fs {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *All) GetConnections() *TcpConnections {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *All) GetListners() []*Listen {
	if x != nil {
		return x.Listners
	}
	return nil
}

func (x *All) GetProtoTalkers() []*NetProtoTalker {
	if x != nil {
		return x.ProtoTalkers
	}
	return nil
}

func (x *All) GetRateTalker() []*NetRateTalker {
	if x != nil {
		return x.RateTalker
	}
	return nil
}

var File_pkg_smgrpc_smgrpc_proto protoreflect.FileDescriptor

var file_pkg_smgrpc_smgrpc_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x6d, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x6d, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x74,
	0x22, 0x50, 0x0a, 0x0e, 0x4e, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x61, 0x6c, 0x6b,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x61,
	0x74, 0x65, 0x22, 0x63, 0x0a, 0x0d, 0x4e, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x54, 0x61, 0x6c,
	0x6b, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x64, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x70, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x62, 0x70, 0x73, 0x22, 0x42, 0x0a, 0x02, 0x46, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x75, 0x73, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x75, 0x73, 0x65, 0x64, 0x22, 0x6a, 0x0a, 0x06, 0x4c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x21, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x41,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3f, 0x0a, 0x03, 0x43, 0x70,
	0x75, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x73, 0x79, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x22, 0x2c, 0x0a, 0x04, 0x44,
	0x69, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x74, 0x70, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x62, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x6b, 0x62, 0x70, 0x73, 0x22, 0x26, 0x0a, 0x0e, 0x54, 0x63, 0x70,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x82, 0x03, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x12, 0x35, 0x0a, 0x0b, 0x6c, 0x6f, 0x61,
	0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x73, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x52, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x1d, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x73, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x70, 0x75, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12,
	0x20, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x73, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x04, 0x64, 0x69, 0x73,
	0x6b, 0x12, 0x2a, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46,
	0x73, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x38, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x63, 0x70, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x6e,
	0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x6d, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x52, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x6e,
	0x65, 0x72, 0x73, 0x12, 0x3a, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x61, 0x6c, 0x6b,
	0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x6d, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4e, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x61, 0x6c, 0x6b, 0x65,
	0x72, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x73, 0x12,
	0x35, 0x0a, 0x0a, 0x72, 0x61, 0x74, 0x65, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x65, 0x74,
	0x52, 0x61, 0x74, 0x65, 0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x52, 0x0a, 0x72, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x32, 0x32, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x2a,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x0f, 0x2e, 0x73, 0x6d, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x73, 0x6d, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x41, 0x6c, 0x6c, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b,
	0x73, 0x6d, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_smgrpc_smgrpc_proto_rawDescOnce sync.Once
	file_pkg_smgrpc_smgrpc_proto_rawDescData = file_pkg_smgrpc_smgrpc_proto_rawDesc
)

func file_pkg_smgrpc_smgrpc_proto_rawDescGZIP() []byte {
	file_pkg_smgrpc_smgrpc_proto_rawDescOnce.Do(func() {
		file_pkg_smgrpc_smgrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_smgrpc_smgrpc_proto_rawDescData)
	})
	return file_pkg_smgrpc_smgrpc_proto_rawDescData
}

var file_pkg_smgrpc_smgrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_smgrpc_smgrpc_proto_goTypes = []interface{}{
	(*Request)(nil),        // 0: smgrpc.Request
	(*NetProtoTalker)(nil), // 1: smgrpc.NetProtoTalker
	(*NetRateTalker)(nil),  // 2: smgrpc.NetRateTalker
	(*Fs)(nil),             // 3: smgrpc.Fs
	(*Listen)(nil),         // 4: smgrpc.Listen
	(*LoadAverage)(nil),    // 5: smgrpc.LoadAverage
	(*Cpu)(nil),            // 6: smgrpc.Cpu
	(*Disk)(nil),           // 7: smgrpc.Disk
	(*TcpConnections)(nil), // 8: smgrpc.TcpConnections
	(*All)(nil),            // 9: smgrpc.All
}
var file_pkg_smgrpc_smgrpc_proto_depIdxs = []int32{
	5, // 0: smgrpc.All.loadAverage:type_name -> smgrpc.LoadAverage
	6, // 1: smgrpc.All.cpu:type_name -> smgrpc.Cpu
	7, // 2: smgrpc.All.disk:type_name -> smgrpc.Disk
	3, // 3: smgrpc.All.partitions:type_name -> smgrpc.Fs
	8, // 4: smgrpc.All.connections:type_name -> smgrpc.TcpConnections
	4, // 5: smgrpc.All.listners:type_name -> smgrpc.Listen
	1, // 6: smgrpc.All.protoTalkers:type_name -> smgrpc.NetProtoTalker
	2, // 7: smgrpc.All.rateTalker:type_name -> smgrpc.NetRateTalker
	0, // 8: smgrpc.Stat.GetAll:input_type -> smgrpc.Request
	9, // 9: smgrpc.Stat.GetAll:output_type -> smgrpc.All
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_smgrpc_smgrpc_proto_init() }
func file_pkg_smgrpc_smgrpc_proto_init() {
	if File_pkg_smgrpc_smgrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_smgrpc_smgrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_smgrpc_smgrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetProtoTalker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_smgrpc_smgrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetRateTalker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_smgrpc_smgrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_smgrpc_smgrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_smgrpc_smgrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadAverage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_smgrpc_smgrpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cpu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_smgrpc_smgrpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Disk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_smgrpc_smgrpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcpConnections); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_smgrpc_smgrpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*All); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_smgrpc_smgrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_smgrpc_smgrpc_proto_goTypes,
		DependencyIndexes: file_pkg_smgrpc_smgrpc_proto_depIdxs,
		MessageInfos:      file_pkg_smgrpc_smgrpc_proto_msgTypes,
	}.Build()
	File_pkg_smgrpc_smgrpc_proto = out.File
	file_pkg_smgrpc_smgrpc_proto_rawDesc = nil
	file_pkg_smgrpc_smgrpc_proto_goTypes = nil
	file_pkg_smgrpc_smgrpc_proto_depIdxs = nil
}
